---
title: "Collaborate"
title-block-banner: images/alternative_2.jpg
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
        /* Use bottom part of the banner image */
        .quarto-title-block .quarto-title-banner {
          background-position: center;
          background-size: cover;
        }
      </style>
bibliography: references.bib
---

::: callout-note
## Submission are open!

We will accept submissions **until Tuesday, November 11, 2025 at 23:59 Central European Time (CET)**.

Submit your short intervention proposal via this survey: [https://stanforduniversity.qualtrics.com/jfe/form/SV_afM7nQCU4wucFTg](https://stanforduniversity.qualtrics.com/jfe/form/SV_afM7nQCU4wucFTg).
:::

# Why should I participate in the project?[^1]

[^1]: This call for collaboration is inspired by other megastudies, in particular @voelkelMegastudyTesting252024

While trust in scientists is moderately high globally, climate scientists are less trusted than scientists in general [@ghasemiGapsPublicTrust2025] and scientists of other disciplines [@gligoricHowSocialEvaluations2024].

Strengthening trust in climate scientists matters: Across 55 countries, trust in climate scientists was the strongest predictors of belief in climate change and support for climate policy [@todorovaMachineLearningIdentifies2025].

Given current attacks on climate science–particularly in the US–and the urgent need to address climate change, more research is needed on how to increase trust in climate scientists. Many people have ideas for how to address this problem. With the *Strengthening Trust in Climate Scientists Megastudy*, we provide the opportunity to gather and rigorously test many of these ideas in a mega experiment.

Join our efforts to make a significant contribution to addressing this issue!

**If your intervention is selected for testing, you will be offered co-authorship (listed in alphabetical order) on the primary publication resulting from the Megastudy.**

# What is an intervention?

Social scientists often call an idea that has the potential to change how people think or behave an "intervention." In our project, an intervention is any idea that may influence the outcome variable we are interested in, namely trust in climate scientists.

# Who can collaborate?

This call is open to researchers at any level, as well as practitioners.

# How many interventions can I propoese?

Interventions can be submitted by individuals or teams, with a **maximum of two individuals** per team. Each team may propose **up to two interventions**, which will be evaluated independently.

Each individual may participate in up to two teams. For example, Peter could submit two interventions as part of a team with Jane, and another two interventions as part of a second team with Martin.

# Who are the participants?

All participants will be based in the US and over the age of 18. Our sample will be a non-probability online sample of Americans that is representative regarding several major demographic benchmarks. Due to filtering based on attention checks, participants can be expected to be relatively attentive to intervention materials.

# What are the requirements for my intervention?

Intervention proposals need to target trust in climate scientists (see details below) and be:

-   Text-based (e.g., no video or audio)
-   Theoretically motivated (rooted in the scientific literature)
-   Online (i.e. deployable in an online survey experiment)
-   Short (no longer than 5 minutes)
-   Costless: (i.e. not paying participants in addition to what they are already being paid to participate in the study)
-   Aligned (e.g., no additional measures for evaluating your intervention can be added)
-   Ethical (the intervention must be approved by Stanford's Institutional Review Board, see details below)

::: callout-tip
## Ethical requirements

Your intervention must provide accurate and true information without exposing participants to unnecessary risks or harm:

-   you may not deceive participants,
-   you may not ask participants to state false beliefs (e.g. ask them to say they trust climate scientists even though they don't),
-   you may not present information to participants that is hateful, disturbing, or offensive,
-   you may not ask participants to engage in hateful or disturbing behaviors.

Further, your intervention must obtain ethics approval by Stanford’s Institutional Review Board (IRB). If your intervention is selected, our team will obtain IRB approval for your intervention. If the IRB requires changes to your intervention, we will work with you to make those changes while maintaining as much consistency as possible to your original idea. You are encouraged to contact us via [{{< var email >}}](mailto:{{< var email >}}) if you have concerns about ethics approval. We will not select interventions that attempt to game the system in some way, e.g., by instructing participants on how to reply to the DVs.
:::

# What are the outcomes?

The outcome that interventions should target is trust in climate scientists (see the [research design section](research_design.qmd) for more details).

An intervention may focus on specific sub-dimensions of trustworthiness (e.g., competence, benevolence, expertise, or openness). However, we will evaluate the efficacy of interventions based on the **average effect across all dimensions**.

Similarly, an intervention may target a specific sub-group of participants (e.g., Republicans). However, the efficacy of interventions will be assessed across the **full sample**, not within individual sub-groups.

# Can I submit different interventions for different participants?

Intervention may target varying participant features. Variables that will be available are age, gender, race, education, and partisan identity. 

For example, an “ingroup source” intervention can use a pro-Democrat source for informing Democrat participants, and a pro-Republican source for informing Republican participants. In this case, the intervention would have the exact same instructions for all participants, but the "ingroup" varies as a function of each participants' partisan affiliation. It is crucial that **all participants receive the same kind of intervention**.

If you have questions whether your intervention satisfies these criteria, you are welcome to [email us](mailto:{{< var email >}}).

# Can I target a specific subgroup of participants? 

You may target a specific subgroup of participants, but the efficacy of your intervention will be evaluated based on its average effect across the entire sample.

# How will you select the interventions?

Our expert team, composed of the research team and an [advisory board](team.qmd), will review submissions and select the most promising interventions for testing. Members of the advisory board are experts on trust in science and behavioral science from diverse backgrounds, including academics from different disciplines as well as practitioners.

We aim to test up to 10 interventions, with a well-powered sample (\~1000 participants per condition).

The selection process is **anonymous**: Only the Project Lead, Jan, knows about the identity of the contributors and will not be involved in the selection process.

The expert team will review interventions to check whether they satisfy the requirements for interventions. They will then select the most promising ones. We will notify you if your intervention does not satisfy the requirements and work with you, within reason, to revise the intervention so that it is eligible. You are welcome to contact us with questions about your intervention before you submit.

The final decision on which interventions will be tested is at the discretion of the advisory board.

# Will I need to contribute in any other way? 

No, your contribution consists only of designing an intervention. We have secured all funding necessary to run the study, and we will design the survey, analyze the data, and write the paper. You will have the opportunity to provide feedback on the paper during the editing phase before it is submitted to a journal.

# Are interactive interventions allowed? 

We are considering interactive intervention proposals (e.g., chatbots) as well. If you plan to submit an interactive intervention, please email us at [{{< var email >}}](mailto:{{< var email >}})!

# How can I participate

Fill out this survey: [https://stanforduniversity.qualtrics.com/jfe/form/SV_afM7nQCU4wucFTg](https://stanforduniversity.qualtrics.com/jfe/form/SV_afM7nQCU4wucFTg)

During this survey, we will ask you to provide a detailed description (max 500 words) of your intervention. 
