---
title: "Research Design"
title-block-banner: images/windmills.jpg
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
        /* Use bottom part of the banner image */
        .quarto-title-block .quarto-title-banner {
          background-position: center;
          background-size: cover;
        }
      </style>
bibliography: references.bib
---

# Motivation

Climate change is one of the most pressing societal issues and requires urgent action at both the policymaking and individual level [@calvinIPCC2023Climate2023; @rogeljCredibilityGapNetzero2023].

Trust in climate scientists is one of the strongest predictors of belief in climate change, support for climate policy, and climate action [@todorovaMachineLearningIdentifies2025; @colognaRoleTrustClimate2020; @hornseyMetaanalysesDeterminantsOutcomes2016].

While trust in scientists is moderately high globally [@colognaTrustScientistsTheir2025], climate scientists have consistently been found to be less trusted than scientists from other fields and scientists in general [@druckmanContinuityChangeTrust2024; @ghasemiInvestigatingTrustGap2024; @schroderDonTellMe; @schugPublicPerceptionsTrustworthiness2024]. Lower trust in climate scientists could hamper societies’ ability to address climate change, resulting in high personal and societal costs.

Increasing trust in climate scientists may therefore be an important lever to accelerate climate action and strengthen societal resilience to climate change. There is currently only a small number of behavioral intervention studies on increasing trust in climate scientists. The STICS project aims to fill this gap.

# Outcomes

Our main outcome of interest is people's perception of climate scientists' trustworthiness. In addition to this, we will also measure attitudes towards climate change, support for climate policies, normative perceptions of climate scientists, and pro-climate behavioral outcomes.

\[tbd\]

# Participants

## Sample size

An a priori power analysis using G\*Power (Faul et al., 2007), shows that for a One Way ANOVA with 10 conditions (9 interventions and one control condition), to achieve 95% power to detect a small effect size f of at least f = 0.05, at an alpha level of 0.05, a sample of N = 9,450 participants is needed. Since the interventions will be tested across population segments, and the approximate size of the segments will be determined in WP1, we err on the conservative side and aim to collect a US sample of N = 10,000 and a Swiss sample of N = 10,000, for a total of N = 20,000 participants, with approximately N = 1,000 participants per condition per country.

Once we have selected interventions, we will run a final power simulation to be included in our preregistration.

## Recruitment

We will recruit representative samples for age, gender, and education in both countries.

# Open science

Following best open-science research practices, a detailed overview of data collection procedures, research questions, and analyses will be preregistered on the Open Science Framework.

Upon publication, all data, code, and materials will be publicly available.

# Timeline

\[tbd\]
